/**
 * Data generators (plan §6 #19): blockstates, block/item models, language files, loot tables and
 * tags are generated by {@code gradlew runData} into {@code src/generated/resources}. Textures and
 * the single static P2P part model stay hand-written resources.
 */
package com.pingsu.appliedember.datagen;
