package com.pingsu.appliedember.content.cell;

import appeng.api.client.StorageCellModels;
import appeng.core.definitions.AEItems;
import appeng.items.storage.StorageTier;
import appeng.items.tools.powered.PortableCellItem;
import appeng.menu.me.common.MEStorageMenu;
import com.pingsu.appliedember.AppliedEmber;
import com.pingsu.appliedember.AppliedEmberResources;
import com.pingsu.appliedember.me.key.EmberKeyType;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.ItemLike;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

/**
 * F1: registration holder for Ember storage cells — the drive cell line, the cell housing and the
 * portable cell.
 *
 * <p>The drive cell line mirrors AE2's own ladder (1k / 4k / 16k / 64k / 256k) so an ember cell is
 * interchangeable with the equivalent AE2 cell; capacity follows AE2's formula
 * {@code (kilobytes * 1024 - bytesPerType * types) * keyType.getAmountPerByte()}, i.e. the 1000 ember
 * per byte from {@link EmberKeyType}. Idle drains are AE2's tier drains too, so keeping an ember cell
 * in a drive costs the same as the item/fluid equivalent.
 *
 * <p>Cells are built from <em>AE2's</em> storage components ({@code ae2:cell_component_<tier>}) rather
 * than components of this mod's own: crafting and clearing a cell therefore hands AE2 items back and
 * forth, and no ember component item exists.
 *
 * <p>The portable cells reuse AE2's generic {@link PortableCellItem} parameterized with
 * {@link EmberKeyType#TYPE} and the stock {@code MEStorageMenu.PORTABLE_ITEM_CELL_TYPE} (AE2 already
 * registers the screen, so no menu code is needed here). They run on AE power like AE2's own portable
 * cells; plan §5-F1 documents what an Ember-powered variant would require instead. One portable cell
 * exists per storage tier, mirroring AE2's {@code portable_item_cell_<tier>} ladder.
 *
 * <p>Item models and lang keys are generated by {@code datagen.EmberItemModelProvider} /
 * {@code EmberLanguageProvider} (plan #19) from the textures in
 * {@code assets/appliedember/textures/item} (housing + per-tier side overlays).
 */
public final class EmberCellContent {

    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, AppliedEmber.MODID);

    /** AE2's customary per-type overhead, in bytes. */
    private static final int BYTES_PER_TYPE = 8;
    /** {@code EmberKey} has no NBT variants, so every cell holds exactly one type. */
    private static final int TOTAL_TYPES = 1;
    /** Ember-orange tint for the portable cell LED. */
    private static final int PORTABLE_CELL_COLOR = 0xD97A00;

    /**
     * One storage tier: the id suffix ({@code 1k}), {@code index} (1-based tier index AE2's drives and
     * upgrade ordering use), the size in kibibytes, the idle drain, and the AE2 storage component the
     * cell is built from.
     */
    public record Tier(String suffix, int index, int kilobytes, double idleDrain, ItemLike aeComponent) {

        public String cellId() {
            return "ember_storage_cell_" + suffix;
        }

        /** Texture used as the tier overlay of the item model, and baked into the drive face. */
        public ResourceLocation sideTexture() {
            return AppliedEmberResources.id("item/embers_storage_cell_side_" + suffix);
        }

        /** Drive-slot model for this tier (see {@link #registerDriveModels()}). */
        public ResourceLocation driveModel() {
            return AppliedEmberResources.id("block/drive/embers_cell_" + suffix);
        }

        /** Registry id of this tier's portable cell. */
        public String portableCellId() {
            return "portable_ember_cell_" + suffix;
        }

        /** Tier overlay of the portable cell item model (AE2's portable side art, per tier). */
        public ResourceLocation portableSideTexture() {
            return AppliedEmberResources.id("item/portable_cell_side_" + suffix);
        }
    }

    /** AE2's tier ladder, with AE2's own idle drains and storage components. */
    private static final List<Tier> TIERS = List.of(
            new Tier("1k", 1, 1, 0.5D, AEItems.CELL_COMPONENT_1K),
            new Tier("4k", 2, 4, 1.0D, AEItems.CELL_COMPONENT_4K),
            new Tier("16k", 3, 16, 1.5D, AEItems.CELL_COMPONENT_16K),
            new Tier("64k", 4, 64, 2.0D, AEItems.CELL_COMPONENT_64K),
            new Tier("256k", 5, 256, 2.5D, AEItems.CELL_COMPONENT_256K));

    /** Housing texture shared by every tier's item model (used by datagen and the drive faces). */
    public static ResourceLocation housingTexture() {
        return AppliedEmberResources.id("item/embers_cell_housing");
    }

    /**
     * Portable-cell layers: the ember-toned screen and housing sit in AE2's portable cell model slots,
     * with AE2's LED and the tier's {@code portable_cell_side_<tier>} overlay completing the same
     * four-layer structure AE2 uses.
     */
    public static ResourceLocation portableScreenTexture() {
        return AppliedEmberResources.id("item/portable_cell_screen");
    }

    public static ResourceLocation portableHousingTexture() {
        return AppliedEmberResources.id("item/portable_cell_fluid_housing");
    }

    public static final RegistryObject<Item> EMBER_CELL_HOUSING = ITEMS.register("ember_cell_housing",
            () -> new Item(new Item.Properties()));

    private static final Map<String, RegistryObject<Item>> CELLS = registerCells();

    /** One portable cell per tier, mirroring AE2's {@code portable_item_cell_<tier>} ladder. */
    private static final Map<String, RegistryObject<Item>> PORTABLE_CELLS = registerPortableCells();

    private static Map<String, RegistryObject<Item>> registerPortableCells() {
        Map<String, RegistryObject<Item>> cells = new LinkedHashMap<>();
        for (Tier tier : TIERS) {
            cells.put(tier.suffix(), ITEMS.register(tier.portableCellId(),
                    () -> new PortableCellItem(
                            EmberKeyType.TYPE,
                            TOTAL_TYPES,
                            MEStorageMenu.PORTABLE_ITEM_CELL_TYPE,
                            new StorageTier(tier.index(), tier.suffix(), tier.kilobytes() * 1024,
                                    tier.idleDrain(), () -> tier.aeComponent().asItem()),
                            new Item.Properties().stacksTo(1),
                            PORTABLE_CELL_COLOR)));
        }
        return Map.copyOf(cells);
    }

    private EmberCellContent() {
    }

    private static Map<String, RegistryObject<Item>> registerCells() {
        Map<String, RegistryObject<Item>> cells = new LinkedHashMap<>();
        for (Tier tier : TIERS) {
            cells.put(tier.suffix(), ITEMS.register(tier.cellId(),
                    () -> new EmberStorageCellItem(
                            new Item.Properties().stacksTo(1),
                            tier.aeComponent(),
                            EMBER_CELL_HOUSING.get(),
                            tier.idleDrain(),
                            tier.kilobytes(),
                            BYTES_PER_TYPE)));
        }
        return Map.copyOf(cells);
    }

    /** Storage tiers in ascending order, for datagen and tests. */
    public static List<Tier> tiers() {
        return TIERS;
    }

    public static RegistryObject<Item> cell(String suffix) {
        return CELLS.get(suffix);
    }

    /** Portable cell of the given tier (same suffixes as {@link #cell(String)}). */
    public static RegistryObject<Item> portableCell(String suffix) {
        return PORTABLE_CELLS.get(suffix);
    }

    /** Every item this class registers, for the creative tab. */
    public static List<Supplier<? extends Item>> allItems() {
        List<Supplier<? extends Item>> items = new ArrayList<>();
        items.add(EMBER_CELL_HOUSING);
        items.addAll(CELLS.values());
        items.addAll(PORTABLE_CELLS.values());
        return List.copyOf(items);
    }

    public static void register(IEventBus modEventBus) {
        ITEMS.register(modEventBus);
    }

    /**
     * Registers the model used to render these cells while inserted in a drive. The faces are baked
     * from the supplied housing plus the tier overlay by {@code tools/gen-drive-faces.ps1}; the
     * individual texture sources stay untouched.
     *
     * <p>Must be called after the item registry has been filled (a {@code RegistryObject} has no value
     * during mod construction — doing this from the constructor throws
     * {@code Registry Object not present}) and before the drive model is baked. The item register
     * event satisfies both: it is the earliest point where the items exist, and it always finishes
     * before the first model bake (unlike {@code FMLClientSetupEvent}, which large packs can run
     * after the initial resource reload has already collected the drive model's dependencies).
     * {@code AppliedEmber} calls this from a LOWEST-priority {@code RegisterEvent} listener.
     */
    public static void registerDriveModels() {
        for (Tier tier : TIERS) {
            StorageCellModels.registerModel(CELLS.get(tier.suffix()).get(), tier.driveModel());
            // The portable tier sits in drives too; it reuses its tier's storage-cell face.
            StorageCellModels.registerModel(PORTABLE_CELLS.get(tier.suffix()).get(), tier.driveModel());
        }
    }
}
